# CI/CD設定(nameは表題やコメントのようなもので、必須ではない)
name: CICD

# 環境変数宣言
env:

  # Javaバージョン
  JAVA_VERSION: '17'

# このGitHubActionsは、次のタイミングで起動する
on:

  # developブランチへのpush時
  push:
    branches: [ "develop" ]

  # developブランチへのプルリクエスト作成時
  pull_request:
    branches: [ "develop" ]

# ジョブ(ワークフロー内で実行する作業のまとまり)の定義
jobs:

  # ビルド設定(buildはjobs配下のジョブ名に該当する、任意の文字列としてよい)
  build:

    # 当該ジョブの実行環境はUbuntuの最新イメージ上とする
    runs-on: ubuntu-latest

#    # GitHubActionsの「ubuntu-latest」はデフォルトでdockerを持っているので、次のように記述することもできる。
#    services:
#      redis:
#        image: redis:latest
#        ports:
#          - "6379:6379"
#        options: >-
#          --health-cmd "redis-cli ping || exit 1"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    # ジョブ内ステップの定義
    steps:

      # ソースコードを取得する
      - name: Checkout repository

        # GitHubActionsが用意しているcheckoutの仕組みで資材を取得する
        uses: actions/checkout@v4

        # Gitサブモジュールを利用する(子プロジェクトあり)
        with:
          submodules: true

      # JDKをセットアップする(ここではJava17を使う)
      - name: Set up JDK 17

        # GitHubActionsが用意しているJDKセットアップの仕組みを利用する
        uses: actions/setup-java@v4

        # Javaのバージョンは17、ディストリビューションはtemurinを利用する
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      # Gradle依存関係のキャッシュ設定
      - name: Cache Gradle packages

        # GitHubActionsが用意している依存関係キャッシュの仕組みを利用する
        uses: actions/cache@v4

        # Gradleキャッシュ、ラッパーを使う(毎回ゼロからGardleビルドしないための、お約束の書き方)
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # docker composeコマンドにより、dockerを起動する。
      - name: Start docker-compose
          docker compose -f ./docker/docker-compose.yml up -d
          docker ps -a  # デバッグ用に起動確認の docker ps コマンドを発行

      # docker配下の各ツールの起動完了を待機する
      - name: Wait for services to be ready
        run: |

          # redisは docker ps コマンドでコンテナIDを取得し、内部でredis-cliにて ping に返信があるまで待機
          until docker exec $(docker ps -qf "ancestor=redis:latest") redis-cli ping | grep PONG; do sleep 3; done

          # Minioについてはヘルスチェック応答があるまで待機することで、起動を確認する (APIポート9000)
          until curl -s http://localhost:9000/minio/health/ready; do sleep 3; done
          echo "All services are ready!"

      # Gradleビルドコマンドで、ビルド＋全テストを実施する
      - name: Build with Gradle
        run: |

          # gradlewファイルに実行権限を付与し、Gradleビルドを実行する
          chmod +x gradlew
          ./gradlew build

      # 後処理として、doker compose downコマンドを実行してdockerを落とす
      - name: Stop docker-compose
        if: always()
        run: docker compose -f ./docker/docker-compose.yml down

      # -------------------------------------------------------------------------------- #
      # CI設定はここまで(ビルドまで)。
      # 以降はCD設定。(dockerイメージビルド及びリポジトリへの配置)
      # -------------------------------------------------------------------------------- #

#      # DockerHubへログインする
#      - name: Log in to DockerHub
#
#        # GitHubActionsが用意しているdockerアクセスの仕組みを利用する
#        uses: docker/login-action@v3
#
#        # DockerHubのユーザ名及びパスワードはGitHubActionsのsecretsから取得する
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      # dockerイメージのビルド及びDockerHubへのイメージ格納(push)
#      - name: Build and push Docker image
#
#        # GitHubActionsが用意しているdockerイメージビルドの仕組みを利用する
#        uses: docker/build-push-action@v5
#
#        # コンテキストはカレントディレクトリ、DockerHubへpushし、タグを付与する
#        with:
#          context: .
#          push: true
#          tags: your-dockerhub-username/sbwap:latest
